# Copyright (C) 2018-2019 Hunan ChenHan Information Technology Co., Ltd.
# 
# SPDX-License-Identifier: GPL-3.0
#
# @author Ding Tao <i@dingtao.org>
#
# @date 9th Jan, 2019
#
# @brief This Makefile is top level of file, it will copy all files in this
#	 directory to final root file system

all: _all

_all:
	cp -R ./files/* ${ROOTFS_DIR}/

.PHONY: _all

