dist: xenial

sudo: required

language: c

addons:
        apt:
                sources:
                        - sourceline: 'ppa:ubuntu-toolchain-r/test'
                packages:
                        - make
                        - binutils-aarch64-linux-gnu
                        - gcc-6-aarch64-linux-gnu
                        - qemu-user-static

script:
        - sudo make

