dist: xenial

sudo: required

language: c

addons:
        apt:
                packages:
                        - make
                        - binutils-arm-linux-gnueabi
                        - gcc-arm-linux-gnueabi
                        - binutils-aarch64-linux-gnu
                        - gcc-aarch64-linux-gnu
                        - qemu-user-static
                        - libc6-dev-i386

script:
        - make && make image

