dist: xenial

sudo: required

language: c

addons:
        apt:
                packages:
                        - make
                        - gcc-aarch64-linux-gnu
                        - libc-dev-arm64-cross
                        - qemu-user-static
                        - git
                        - device-tree-compiler
                        - gcc-arm-linux-gnueabi
                        - libc-dev-armhf-cross
                        - libc-dev-armel-cross

script:
        - sudo make

