dist: xenial

sudo: required

language: c

addons:
        apt:
                packages:
                        - make
                        - qemu-user-static

script:
        - sudo make image

