dist: xenial

language: c

addons:
        apt:
                packages:
                        - make
                        - gcc-aarch64-linux-gnu
                        - binutils-aarch64-linux-gnu
                        - qemu-user-static
                        - libc6-dev-i386
                        - linux-libc-dev
                        - libx32gcc-5-dev

script:
        - make && make image

