dist: xenial

sudo: required

language: c

addons:
        apt:
                packages:
                        - make
                        - binutils-aarch64-linux-gnu
                        - gcc-aarch64-linux-gnu
                        - gcc-multilib
                        - qemu-user-static
                        - libc6-dev-i386

before_install:
        - sudo ln -s /usr/include/asm-generic /usr/include/asm

script:
        - make && sudo make image

