dist: xenial

addons:
        apt:
                packages:
                        - make
                        - gcc-aarch64-linux-gnu
                        - binutils-aarch64-linux-gnu
                        - qemu-user-static
                        - libc6
                        - libc6-dev
                        - libc6-dev-i386

script:
        - make && make image

