dist: xenial

sudo: required

language: c

addons:
        apt:
                packages:
                        - make
                        - gcc-aarch64-linux-gnu
                        - qemu-user-static

script:
        - sudo make image

