dist: xenial

sudo: required

language: c

addons:
        apt:
                sources:
                        - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
                packages:
                        - make
                        - gcc-arm-embedded
                        - qemu-user-static

script:
        - sudo make

