dist: xenial

addons:
        apt:
                packages:
                        - make
                        - gcc-aarch64-linux-gnu
                        - binutils-aarch64-linux-gnu
                        - libc6-arm64-cross
                        - qemu-user-static

script:
        - make && make image

