# Copyright (C) 2018-2019 Hunan ChenHan Information Technology Co., Ltd.
#
# SPDX-License-Identifier: GPL-3.0
#
# @author Ding Tao <i@dingtao.org>
#
# @date 9th Jan, 2019
#
# @brief This Makefile is a good tools to generate Ubuntu rootfs by adding our
#	 own files.

all: change_root

change_root:
	./change_root.sh $(ROOTFS_DIR)

.PHONY: change_root
